options:
  port:
    type: int
    default: 80
    description: |
      NGINX listen port
  host:
    type: string
    default: "0.0.0.0"
    description: listen address
  commit:
    type: string
    default: !!null 
    description: commit to update to
  repo:
    type: string
    default: !!null 
    description: The repository to clone from, this is required
  deploy-key:
    type: string
    default: 
    description: |
      A deploy key is an SSH key that is stored on the server and
      grants access to a repository.
  key-required:
    type: boolean
    default: !!bool false
    description: |
      This should be set to true to ensure that a deploy key is
      deployed if necessary
